pipeline {
    agent any
    stages {
        stage('---clean---') {
            steps {
                bat "mvn clean -f C:\Users\simranjain\git\repository9\employee\pom.xml"
            }
        }
        stage('--test--') {
            steps {
                bat "mvn test -f C:\Users\simranjain\git\repository9\employee\pom.xml"
            }
        }
        stage('--package--') {
            steps {
                bat "mvn package -f C:\Users\simranjain\git\repository9\employee\pom.xml"
            }
        }
     
    }
}
